### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by Fale** [PuerkitoBio/urlesc#1]
Hi,
I'm trying build this for Fedora, but it's failing a couple of tests.

```
urlesc_test.go:367: Escape(Parse("http://%3Fam:pa%3Fsword@google.com")) == "http://?am:pa?sword@google.com" (expected "http://%3Fam:pa%3Fsword@google.com")
urlesc_test.go:367: Escape(Parse("http://%3A%2F%3F:%23%5B%5D%40@example.com")) == "http://%3A%2F?:%23%5B%5D%40@example.com" (expected "http://%3A%2F%3F:%23%5B%5D%40@example.com")
```

You can find the whole build session at https://kojipkgs.fedoraproject.org//work/tasks/8917/9358917/build.log

Here there are even more information about the environment: https://kojipkgs.fedoraproject.org//work/tasks/8917/9358917/root.log

Maybe there is some problems with golang 1.3.3? Or something about ARM platform?

**Comment by ghost** [comment]
@Fale  It's due to a bug in Go 1.3 (see [issue 6573](https://github.com/golang/go/issues/6573)).

**Comment by Fale** [comment]
Thanks :)
